//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Game/Scripts/GameScripts/GameInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Game/Scripts/GameScripts/GameInputAction.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @GameInputAction: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @GameInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""GameInputAction"",
    ""maps"": [
        {
            ""name"": ""GameKey"",
            ""id"": ""d7ca974c-50e8-417a-b282-1449088fac2c"",
            ""actions"": [
                {
                    ""name"": ""KKey"",
                    ""type"": ""Button"",
                    ""id"": ""e831cead-dff7-4976-982b-a8422ce14ac3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""JKey"",
                    ""type"": ""Button"",
                    ""id"": ""7ea2868b-7ac8-4fc7-8e48-e498d1c7e878"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FKey"",
                    ""type"": ""Button"",
                    ""id"": ""f7024f5c-1a2b-4770-bc0f-0d5ee96ddd75"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DKey"",
                    ""type"": ""Button"",
                    ""id"": ""c6fc1688-4aef-4ec8-a5b1-30bf549abcd1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""28dab9db-5732-458f-a649-a04b6e22537b"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4fc68746-9de7-4dee-8816-e6cc58cadb9d"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd07f55c-b2ab-4e94-bf05-19add29c7b3e"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3ba9fe2-87d1-4d7b-b019-8a13a7b63b2f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // GameKey
        m_GameKey = asset.FindActionMap("GameKey", throwIfNotFound: true);
        m_GameKey_KKey = m_GameKey.FindAction("KKey", throwIfNotFound: true);
        m_GameKey_JKey = m_GameKey.FindAction("JKey", throwIfNotFound: true);
        m_GameKey_FKey = m_GameKey.FindAction("FKey", throwIfNotFound: true);
        m_GameKey_DKey = m_GameKey.FindAction("DKey", throwIfNotFound: true);
    }

    ~@GameInputAction()
    {
        UnityEngine.Debug.Assert(!m_GameKey.enabled, "This will cause a leak and performance issues, GameInputAction.GameKey.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // GameKey
    private readonly InputActionMap m_GameKey;
    private List<IGameKeyActions> m_GameKeyActionsCallbackInterfaces = new List<IGameKeyActions>();
    private readonly InputAction m_GameKey_KKey;
    private readonly InputAction m_GameKey_JKey;
    private readonly InputAction m_GameKey_FKey;
    private readonly InputAction m_GameKey_DKey;
    /// <summary>
    /// Provides access to input actions defined in input action map "GameKey".
    /// </summary>
    public struct GameKeyActions
    {
        private @GameInputAction m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public GameKeyActions(@GameInputAction wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "GameKey/KKey".
        /// </summary>
        public InputAction @KKey => m_Wrapper.m_GameKey_KKey;
        /// <summary>
        /// Provides access to the underlying input action "GameKey/JKey".
        /// </summary>
        public InputAction @JKey => m_Wrapper.m_GameKey_JKey;
        /// <summary>
        /// Provides access to the underlying input action "GameKey/FKey".
        /// </summary>
        public InputAction @FKey => m_Wrapper.m_GameKey_FKey;
        /// <summary>
        /// Provides access to the underlying input action "GameKey/DKey".
        /// </summary>
        public InputAction @DKey => m_Wrapper.m_GameKey_DKey;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_GameKey; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="GameKeyActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(GameKeyActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="GameKeyActions" />
        public void AddCallbacks(IGameKeyActions instance)
        {
            if (instance == null || m_Wrapper.m_GameKeyActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GameKeyActionsCallbackInterfaces.Add(instance);
            @KKey.started += instance.OnKKey;
            @KKey.performed += instance.OnKKey;
            @KKey.canceled += instance.OnKKey;
            @JKey.started += instance.OnJKey;
            @JKey.performed += instance.OnJKey;
            @JKey.canceled += instance.OnJKey;
            @FKey.started += instance.OnFKey;
            @FKey.performed += instance.OnFKey;
            @FKey.canceled += instance.OnFKey;
            @DKey.started += instance.OnDKey;
            @DKey.performed += instance.OnDKey;
            @DKey.canceled += instance.OnDKey;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="GameKeyActions" />
        private void UnregisterCallbacks(IGameKeyActions instance)
        {
            @KKey.started -= instance.OnKKey;
            @KKey.performed -= instance.OnKKey;
            @KKey.canceled -= instance.OnKKey;
            @JKey.started -= instance.OnJKey;
            @JKey.performed -= instance.OnJKey;
            @JKey.canceled -= instance.OnJKey;
            @FKey.started -= instance.OnFKey;
            @FKey.performed -= instance.OnFKey;
            @FKey.canceled -= instance.OnFKey;
            @DKey.started -= instance.OnDKey;
            @DKey.performed -= instance.OnDKey;
            @DKey.canceled -= instance.OnDKey;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="GameKeyActions.UnregisterCallbacks(IGameKeyActions)" />.
        /// </summary>
        /// <seealso cref="GameKeyActions.UnregisterCallbacks(IGameKeyActions)" />
        public void RemoveCallbacks(IGameKeyActions instance)
        {
            if (m_Wrapper.m_GameKeyActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="GameKeyActions.AddCallbacks(IGameKeyActions)" />
        /// <seealso cref="GameKeyActions.RemoveCallbacks(IGameKeyActions)" />
        /// <seealso cref="GameKeyActions.UnregisterCallbacks(IGameKeyActions)" />
        public void SetCallbacks(IGameKeyActions instance)
        {
            foreach (var item in m_Wrapper.m_GameKeyActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GameKeyActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="GameKeyActions" /> instance referencing this action map.
    /// </summary>
    public GameKeyActions @GameKey => new GameKeyActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "GameKey" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="GameKeyActions.AddCallbacks(IGameKeyActions)" />
    /// <seealso cref="GameKeyActions.RemoveCallbacks(IGameKeyActions)" />
    public interface IGameKeyActions
    {
        /// <summary>
        /// Method invoked when associated input action "KKey" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnKKey(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "JKey" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnJKey(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "FKey" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFKey(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "DKey" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDKey(InputAction.CallbackContext context);
    }
}
